/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PONG_PRIVATE_H
#define PONG_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.407"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	407
#define COMPANY_NAME	""
#define FILE_VERSION	"0.0.0.407"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.0.0.407"

#endif /*PONG_PRIVATE_H*/
